language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
    allow_failures:
        - php: nightly

before_script:
  - travis_wait composer self-update
  - travis_wait composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/test-reporter

services:
  - redis-server

addons:
  code_climate:
    repo_token: c169da2961829181a4c1c3dbb4e51a4d7f3e0f9f260730145518de6652b37564

env:
  - REDIS_CLIENT=phpredis
